name: fat-ml
channels:
- soumith
- defaults
dependencies:
- jupyter

- matplotlib
- numpy
- pandas
- pillow
- pip
- python>=3.6

- six
- sqlalchemy>=1.1
- sqlite>=3.13

#- cuda80=1.0=0 #Go with the regular CUDA install and pytorch from source way!
#- pytorch=0.1.12=py36_2cu80
#- torchvision=0.1.8=py36_2
- pip:
  - annoy>=1.9.1
  - configargparse>=0.12.0
  - dash
  - dash-core-components
  - dash-html-components
  - dash-renderer
  - plotly
  - dogpile.cache
  - flasgger
  - flask>=0.12.2
  - gunicorn
  - jupyterthemes
  - requests
  - tensorflow-gpu